#!/bin/bash
#SBATCH --partition VC5
#SBATCH --gres gpu:4
#SBATCH --ntasks 1
#SBATCH --ntasks-per-node 1
#SBATCH --quotatype spot
#SBATCH --job-name inference_hf_MiniCPM-V
#SBATCH --output logs_eval/MiniCPM-V/evaluation.log
#SBATCH --error logs_eval/MiniCPM-V/evaluation.log
# args: -p
# args: VC5
# args: --gres=gpu:4
# args: --ntasks=1
# args: --ntasks-per-node=1
# args: --quotatype=spot
# args: --job-name=inference_hf_MiniCPM-V
# args: -e
# args: logs_eval/MiniCPM-V/evaluation.log
# args: env
# args: PATH=/usr/local/cuda-12.2/bin:/usr/local/cuda-12.2/bin:/mnt/petrelfs/chenlianjie.p/miniconda3/envs/myenv/bin:/mnt/petrelfs/chenlianjie.p/miniconda3/bin:/mnt/petrelfs/chenlianjie.p/.pyenv/shims:/mnt/petrelfs/chenlianjie.p/.pyenv/bin:/mnt/hwfile/chenlianjie.p/.vscode-server/cli/servers/Stable-e54c774e0add60467559eb0d1e229c6452cf8447/server/bin/remote-cli:/mnt/petrelfs/chenlianjie.p/.pyenv/bin:/mnt/petrelfs/chenlianjie.p/.pyenv/bin:/mnt/petrelfs/chenlianjie.p/.pyenv/bin:/mnt/petrelfs/chenlianjie.p/miniconda3/bin:/mnt/petrelfs/chenlianjie.p/miniconda3/condabin:/mnt/petrelfs/chenlianjie.p/.pyenv/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/mnt/petrelfs/chenlianjie.p/.local/bin:/mnt/petrelfs/chenlianjie.p/bin:/mnt/petrelfs/chenlianjie.p/.local/bin:/mnt/petrelfs/chenlianjie.p/bin:/mnt/petrelfs/chenlianjie.p/.vscode-server/extensions/ms-python.debugpy-2025.0.1/bundled/scripts/noConfigScripts
# args: LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64:/usr/local/cuda-12.2/lib64:
# args: bash
# args: -c
# args: if ! python -c 'import flash_attn' &> /dev/null; then               echo 'flash-attn 未安装，正在安装...';               pip install flash-attn;           else               echo 'flash-attn 已安装';           fi;           export http_proxy=http://chenlianjie.p:N9CiXqoEygZkKXe6x2nchSAzxQDKmtzNDTP2iQ4IWepVUo0Z7q7PJHRVseOw@10.1.20.51:23128/;           export https_proxy=http://chenlianjie.p:N9CiXqoEygZkKXe6x2nchSAzxQDKmtzNDTP2iQ4IWepVUo0Z7q7PJHRVseOw@10.1.20.51:23128/;           python -u test.py --verbose
argv=()
while read -r line; do
    if [[ $line == "# args: "* ]]; then
        argv[${#argv[*]}]="${line:8}"
    fi
done < $0

srun "${argv[@]}"
